kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:dind 
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock

  environment:
    USER:
      from_secret: user
    PAT:
      from_secret: pat

  commands:
  - docker --version
  - echo $USER
  - echo $PAT | docker login ghcr.io -u USER --password-stdin
  - docker build -t ghcr.io/oldzii/frontend ./docker/production/Dockerfile
  - docker push ghcr.io/Oldzii/frontend 
  - echo done


volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

