version: "3.8"

services:
  app:
    container_name: frontend-prod
    image: frontend-prod
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile  
      target: production
    ports:
      - 8080:8080
