version: "3.3"

services:
  app:
    container_name: frontend-dev
    image: frontend-dev
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
