kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:dind 
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock

  environment:
    USER:
      from_secret: user
    PASSWORD:
      from_secret: password

  commands:
  - echo working

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

