kind: pipeline
type: docker
name: default

steps:
- name: lint
  commands:
    - echo "lint to do"

- name: build
  image: docker:dind 
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock

  environment:
    USER:
      from_secret: user
    PAT:
      from_secret: pat

  commands:
  - docker build -t  ghcr.io/oldzii/frontend ./frontend/. --file ./frontend/docker/production/Dockerfile
  - echo "build done"

- name: test
  image: docker:dind
  command:
    - echo "testing to do"

- name: push
  image: docker:dind
  when:
    branch:
    - mock_master
    - develop
    - master
    - echo $PAT | docker login ghcr.io -u USER --password-stdin
    - docker push ghcr.io/oldzii/frontend 

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

