version: "3.9"

services:
  app:
    container_name: frontend-dev
    image: frontend-dev
    build:
      context: ./frontend/.
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
