version: "3.9"

services:
  app:
    container_name: frontend-dev
    image: frontend-dev
    build:
      context: ./frontend/.
      dockerfile: ./docker/development/Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000

  db:
    container_name: db
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db/db-data/:/var/lib/postgresql/data/
      - ./db/dump.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    container_name: backend
    build:
      context: ./backend/.
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend/src:/backend
    ports:
      - 9999:9999
  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
