version: "3.9"

services:
  # app:
  #   container_name: frontend-dev
  #   image: frontend-dev
  #   build:
  #     context: ./frontend/.
  #     dockerfile: ./docker/development/Dockerfile
  #   volumes:
  #     - ./frontend/src:/app/src
  #   ports:
  #     - 3000:3000

  db:
    container_name: db
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=leasing_shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leasing_shop
    volumes:
      - ./backend/docker/db-data/:/var/lib/postgresql/data/
      - ./backend/docker/dump.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    container_name: backend
    build:
      context: ./backend/.
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend/src:/backend
    ports:
      - 9999:9999
  # pg_admin:
  #   container_name: pg_admin
  #   image: dpage/pgadmin4

  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
